# Generated by Django 2.2.14 on 2021-03-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodCourt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_delivery',
            name='card_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order_delivery',
            name='cvv',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order_delivery',
            name='expirydate',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
