# Generated by Django 2.2.14 on 2021-03-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodCourt', '0002_auto_20210325_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_order',
            name='transaction_id',
        ),
    ]
