# Generated by Django 2.2.14 on 2021-03-29 06:06

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('FoodCourt', '0003_remove_customer_order_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=200)),
                ('admin_email', models.CharField(max_length=200)),
                ('admin_phone', models.IntegerField()),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='addfood',
            fields=[
                ('addfoodid', models.AutoField(primary_key=True, serialize=False)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodCourt.Admin')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodCourt.Food')),
            ],
        ),
    ]
